CRITICAL - 2024-12-13 15:48:10 --> ErrorException: require(/home/shivam/www/myCodeIg/vendor/autoload.php): Failed to open stream: No such file or directory
[Method: CLI, Route: serve]
in APPPATH\Commands\SendNotification.php on line 9.
 1 APPPATH\Commands\SendNotification.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(/home/shivam/www/myCodeIg/vendor/autoload.php): Failed to open stream: No such file or directory', 'D:\\ci\\todo\\app\\Commands\\SendNotification.php', 9)
 2 APPPATH\Commands\SendNotification.php(9): require()
 3 VENDORPATH\composer\ClassLoader.php(576): include('D:\\ci\\todo\\app\\Commands\\SendNotification.php')
 4 VENDORPATH\composer\ClassLoader.php(427): Composer\Autoload\{closure}('D:\\ci\\todo\\vendor\\composer/../../app/Commands/SendNotification.php')
 5 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Commands\\SendNotification')
 6 SYSTEMPATH\Autoloader\FileLocator.php(306): class_exists('App\\Commands\\SendNotification')
 7 SYSTEMPATH\CLI\Commands.php(112): CodeIgniter\Autoloader\FileLocator->findQualifiedNameFromPath('D:\\ci\\todo\\app\\Commands\\SendNotification.php')
 8 SYSTEMPATH\CLI\Commands.php(49): CodeIgniter\CLI\Commands->discoverCommands()
 9 SYSTEMPATH\Config\Services.php(178): CodeIgniter\CLI\Commands->__construct()
10 SYSTEMPATH\Config\BaseService.php(312): CodeIgniter\Config\Services::commands(false)
11 SYSTEMPATH\Config\BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('commands', [...])
12 SYSTEMPATH\Config\Services.php(175): CodeIgniter\Config\BaseService::getSharedInstance('commands')
13 SYSTEMPATH\Config\BaseService.php(321): CodeIgniter\Config\Services::commands()
14 SYSTEMPATH\CLI\Console.php(43): CodeIgniter\Config\BaseService::__callStatic('commands', [])
15 SYSTEMPATH\Boot.php(351): CodeIgniter\CLI\Console->run()
16 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
17 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
CRITICAL - 2024-12-13 15:52:29 --> ErrorException: require(/home/shivam/www/myCodeIg/vendor/autoload.php): Failed to open stream: No such file or directory
[Method: CLI, Route: serve]
in APPPATH\Commands\SendNotification.php on line 9.
 1 APPPATH\Commands\SendNotification.php(9): CodeIgniter\Debug\Exceptions->errorHandler(2, 'require(/home/shivam/www/myCodeIg/vendor/autoload.php): Failed to open stream: No such file or directory', 'D:\\ci\\todo\\app\\Commands\\SendNotification.php', 9)
 2 APPPATH\Commands\SendNotification.php(9): require()
 3 VENDORPATH\composer\ClassLoader.php(576): include('D:\\ci\\todo\\app\\Commands\\SendNotification.php')
 4 VENDORPATH\composer\ClassLoader.php(427): Composer\Autoload\{closure}('D:\\ci\\todo\\vendor\\composer/../../app/Commands/SendNotification.php')
 5 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Commands\\SendNotification')
 6 SYSTEMPATH\Autoloader\FileLocator.php(306): class_exists('App\\Commands\\SendNotification')
 7 SYSTEMPATH\CLI\Commands.php(112): CodeIgniter\Autoloader\FileLocator->findQualifiedNameFromPath('D:\\ci\\todo\\app\\Commands\\SendNotification.php')
 8 SYSTEMPATH\CLI\Commands.php(49): CodeIgniter\CLI\Commands->discoverCommands()
 9 SYSTEMPATH\Config\Services.php(178): CodeIgniter\CLI\Commands->__construct()
10 SYSTEMPATH\Config\BaseService.php(312): CodeIgniter\Config\Services::commands(false)
11 SYSTEMPATH\Config\BaseService.php(251): CodeIgniter\Config\BaseService::__callStatic('commands', [...])
12 SYSTEMPATH\Config\Services.php(175): CodeIgniter\Config\BaseService::getSharedInstance('commands')
13 SYSTEMPATH\Config\BaseService.php(321): CodeIgniter\Config\Services::commands()
14 SYSTEMPATH\CLI\Console.php(43): CodeIgniter\Config\BaseService::__callStatic('commands', [])
15 SYSTEMPATH\Boot.php(351): CodeIgniter\CLI\Console->run()
16 SYSTEMPATH\Boot.php(104): CodeIgniter\Boot::runCommand(Object(CodeIgniter\CLI\Console))
17 ROOTPATH\spark(84): CodeIgniter\Boot::bootSpark(Object(Config\Paths))
ERROR - 2024-12-13 15:55:44 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'task_manager', 3306, '', 0)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#4 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#5 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#6 D:\ci\todo\app\Models\UserModel.php(43): CodeIgniter\BaseModel->first()
#7 D:\ci\todo\app\Controllers\AuthController.php(34): App\Models\UserModel->validateCredentials('shiva83023@gmai...', '123')
#8 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->loginUser()
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#15 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *\nFROM `...', Array, false)
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
#4 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(714): CodeIgniter\Model->doFirst()
#5 D:\ci\todo\app\Models\UserModel.php(43): CodeIgniter\BaseModel->first()
#6 D:\ci\todo\app\Controllers\AuthController.php(34): App\Models\UserModel->validateCredentials('shiva83023@gmai...', '123')
#7 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->loginUser()
#8 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#11 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#12 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#13 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#14 {main}
CRITICAL - 2024-12-13 15:55:44 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: login]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(1644): CodeIgniter\Database\BaseConnection->query('SELECT *
FROM `users`
WHERE `email` = :email:
 LIMIT 1', [...], false)
 3 SYSTEMPATH\Model.php(330): CodeIgniter\Database\BaseBuilder->get()
 4 SYSTEMPATH\BaseModel.php(714): CodeIgniter\Model->doFirst()
 5 APPPATH\Models\UserModel.php(43): CodeIgniter\BaseModel->first()
 6 APPPATH\Controllers\AuthController.php(34): App\Models\UserModel->validateCredentials('shiva83023@gmail.com', '123')
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->loginUser()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
ERROR - 2024-12-13 16:02:13 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'task_manager', 3306, '', 0)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\ci\todo\app\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save(Array)
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#7 D:\ci\todo\app\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save(Array)
#8 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#15 {main}
CRITICAL - 2024-12-13 16:02:13 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
ERROR - 2024-12-13 16:02:45 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'task_manager', 3306, '', 0)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\ci\todo\app\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save(Array)
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#7 D:\ci\todo\app\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save(Array)
#8 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#15 {main}
CRITICAL - 2024-12-13 16:02:45 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
ERROR - 2024-12-13 16:02:56 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'task_manager', 3306, '', 0)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\ci\todo\app\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save(Array)
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#7 D:\ci\todo\app\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save(Array)
#8 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#15 {main}
CRITICAL - 2024-12-13 16:02:56 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
ERROR - 2024-12-13 16:03:01 --> Error connecting to the database: mysqli_sql_exception: Access denied for user 'root'@'localhost' (using password: YES) in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:186
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(186): mysqli->real_connect('127.0.0.1', 'root', Object(SensitiveParameterValue), 'task_manager', 3306, '', 0)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\ci\todo\app\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save(Array)
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#16 {main}

Next CodeIgniter\Database\Exceptions\DatabaseException: Access denied for user '****'@'localhost' (using password: YES) in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:231
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(421): CodeIgniter\Database\MySQLi\Connection->connect(false)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#4 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#5 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#7 D:\ci\todo\app\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save(Array)
#8 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#11 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#13 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#14 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#15 {main}
CRITICAL - 2024-12-13 16:03:01 --> CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user '****'@'localhost' (using password: YES)
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 467.
 1 SYSTEMPATH\Database\BaseConnection.php(616): CodeIgniter\Database\BaseConnection->initialize()
 2 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 3 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 4 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 5 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 6 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 7 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
 8 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
 9 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
10 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
11 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
12 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
13 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
14 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
ERROR - 2024-12-13 16:06:04 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\ci\todo\app\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save(Array)
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#16 {main}
CRITICAL - 2024-12-13 16:06:04 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:06:04 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$WSeQXBF1ChBzCUkV7nWHUug5MaNfs1qJBuqaV7kf8Z.nKrVbZDpV2\', \'1\', \'2024-12-13 16:06:04\', \'2024-12-13 16:06:04\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$WSeQXBF1ChBzCUkV7nWHUug5MaNfs1qJBuqaV7kf8Z.nKrVbZDpV2\', \'1\', \'2024-12-13 16:06:04\', \'2024-12-13 16:06:04\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:06:04 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$WSeQXBF1ChBzCUkV7nWHUug5MaNfs1qJBuqaV7kf8Z.nKrVbZDpV2\', \'1\', \'2024-12-13 16:06:04\', \'2024-12-13 16:06:04\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$WSeQXBF1ChBzCUkV7nWHUug5MaNfs1qJBuqaV7kf8Z.nKrVbZDpV2\', \'1\', \'2024-12-13 16:06:04\', \'2024-12-13 16:06:04\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$WSeQXBF1ChBzCUkV7nWHUug5MaNfs1qJBuqaV7kf8Z.nKrVbZDpV2\', \'1\', \'2024-12-13 16:06:04\', \'2024-12-13 16:06:04\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
ERROR - 2024-12-13 16:06:51 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\ci\todo\app\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save(Array)
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#16 {main}
CRITICAL - 2024-12-13 16:06:51 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:06:51 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$H29.e0lG7fSfEi8nZLuTDO2IJJDzlW73j./dtsZ4.DWwTSPpARzBS\', \'1\', \'2024-12-13 16:06:51\', \'2024-12-13 16:06:51\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$H29.e0lG7fSfEi8nZLuTDO2IJJDzlW73j./dtsZ4.DWwTSPpARzBS\', \'1\', \'2024-12-13 16:06:51\', \'2024-12-13 16:06:51\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:06:51 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$H29.e0lG7fSfEi8nZLuTDO2IJJDzlW73j./dtsZ4.DWwTSPpARzBS\', \'1\', \'2024-12-13 16:06:51\', \'2024-12-13 16:06:51\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$H29.e0lG7fSfEi8nZLuTDO2IJJDzlW73j./dtsZ4.DWwTSPpARzBS\', \'1\', \'2024-12-13 16:06:51\', \'2024-12-13 16:06:51\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$H29.e0lG7fSfEi8nZLuTDO2IJJDzlW73j./dtsZ4.DWwTSPpARzBS\', \'1\', \'2024-12-13 16:06:51\', \'2024-12-13 16:06:51\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
ERROR - 2024-12-13 16:15:40 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\ci\todo\app\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save(Array)
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#16 {main}
CRITICAL - 2024-12-13 16:15:40 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:15:40 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$.vJV.0hTxOnjoZYBMCSvaubkrIbh/Pf2ZLPJnCRKdsr1KyO8B2p1q\', \'1\', \'2024-12-13 16:15:40\', \'2024-12-13 16:15:40\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$.vJV.0hTxOnjoZYBMCSvaubkrIbh/Pf2ZLPJnCRKdsr1KyO8B2p1q\', \'1\', \'2024-12-13 16:15:40\', \'2024-12-13 16:15:40\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:15:40 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$.vJV.0hTxOnjoZYBMCSvaubkrIbh/Pf2ZLPJnCRKdsr1KyO8B2p1q\', \'1\', \'2024-12-13 16:15:40\', \'2024-12-13 16:15:40\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$.vJV.0hTxOnjoZYBMCSvaubkrIbh/Pf2ZLPJnCRKdsr1KyO8B2p1q\', \'1\', \'2024-12-13 16:15:40\', \'2024-12-13 16:15:40\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$.vJV.0hTxOnjoZYBMCSvaubkrIbh/Pf2ZLPJnCRKdsr1KyO8B2p1q\', \'1\', \'2024-12-13 16:15:40\', \'2024-12-13 16:15:40\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
ERROR - 2024-12-13 16:19:17 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\ci\todo\app\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save(Array)
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#16 {main}
CRITICAL - 2024-12-13 16:19:17 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:19:17 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$jACnak3z0fCMRa.Bblyc0OktVV.d3db5iakaKv6GDDgMx8NMA.xUy\', \'1\', \'2024-12-13 16:19:17\', \'2024-12-13 16:19:17\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$jACnak3z0fCMRa.Bblyc0OktVV.d3db5iakaKv6GDDgMx8NMA.xUy\', \'1\', \'2024-12-13 16:19:17\', \'2024-12-13 16:19:17\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:19:17 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$jACnak3z0fCMRa.Bblyc0OktVV.d3db5iakaKv6GDDgMx8NMA.xUy\', \'1\', \'2024-12-13 16:19:17\', \'2024-12-13 16:19:17\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$jACnak3z0fCMRa.Bblyc0OktVV.d3db5iakaKv6GDDgMx8NMA.xUy\', \'1\', \'2024-12-13 16:19:17\', \'2024-12-13 16:19:17\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'shiva83023@gmail.com\', \'$2y$10$jACnak3z0fCMRa.Bblyc0OktVV.d3db5iakaKv6GDDgMx8NMA.xUy\', \'1\', \'2024-12-13 16:19:17\', \'2024-12-13 16:19:17\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\AuthController.php(88): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
ERROR - 2024-12-13 16:23:43 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\ci\todo\app\Controllers\AuthController.php(89): CodeIgniter\BaseModel->save(Array)
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#16 {main}
CRITICAL - 2024-12-13 16:23:43 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AuthController.php(89): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:23:43 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'vishwakarma888115@gmail.com\', \'$2y$10$Tazr9nWaBzqRxZgCDe.Gl.JwYJ5jep6BsUREEINlnWoc9OMDYvuWG\', \'1\', \'2024-12-13 16:23:43\', \'2024-12-13 16:23:43\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'vishwakarma888115@gmail.com\', \'$2y$10$Tazr9nWaBzqRxZgCDe.Gl.JwYJ5jep6BsUREEINlnWoc9OMDYvuWG\', \'1\', \'2024-12-13 16:23:43\', \'2024-12-13 16:23:43\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\AuthController.php(89): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:23:43 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'vishwakarma888115@gmail.com\', \'$2y$10$Tazr9nWaBzqRxZgCDe.Gl.JwYJ5jep6BsUREEINlnWoc9OMDYvuWG\', \'1\', \'2024-12-13 16:23:43\', \'2024-12-13 16:23:43\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'vishwakarma888115@gmail.com\', \'$2y$10$Tazr9nWaBzqRxZgCDe.Gl.JwYJ5jep6BsUREEINlnWoc9OMDYvuWG\', \'1\', \'2024-12-13 16:23:43\', \'2024-12-13 16:23:43\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'Shivam\', \'vishwakarma888115@gmail.com\', \'$2y$10$Tazr9nWaBzqRxZgCDe.Gl.JwYJ5jep6BsUREEINlnWoc9OMDYvuWG\', \'1\', \'2024-12-13 16:23:43\', \'2024-12-13 16:23:43\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\AuthController.php(89): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
ERROR - 2024-12-13 16:32:42 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\ci\todo\app\Controllers\AuthController.php(89): CodeIgniter\BaseModel->save(Array)
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#16 {main}
CRITICAL - 2024-12-13 16:32:42 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AuthController.php(89): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:32:42 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'sdasd\', \'vishwakarma888115@gmail.com\', \'$2y$10$s1wugzNe89tw.c5/ZzhzO.zOmwa/jn0rrKmSUkldAksVvmk71/nYq\', \'1\', \'2024-12-13 16:32:42\', \'2024-12-13 16:32:42\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'sdasd\', \'vishwakarma888115@gmail.com\', \'$2y$10$s1wugzNe89tw.c5/ZzhzO.zOmwa/jn0rrKmSUkldAksVvmk71/nYq\', \'1\', \'2024-12-13 16:32:42\', \'2024-12-13 16:32:42\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\AuthController.php(89): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:32:42 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'sdasd\', \'vishwakarma888115@gmail.com\', \'$2y$10$s1wugzNe89tw.c5/ZzhzO.zOmwa/jn0rrKmSUkldAksVvmk71/nYq\', \'1\', \'2024-12-13 16:32:42\', \'2024-12-13 16:32:42\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'sdasd\', \'vishwakarma888115@gmail.com\', \'$2y$10$s1wugzNe89tw.c5/ZzhzO.zOmwa/jn0rrKmSUkldAksVvmk71/nYq\', \'1\', \'2024-12-13 16:32:42\', \'2024-12-13 16:32:42\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'sdasd\', \'vishwakarma888115@gmail.com\', \'$2y$10$s1wugzNe89tw.c5/ZzhzO.zOmwa/jn0rrKmSUkldAksVvmk71/nYq\', \'1\', \'2024-12-13 16:32:42\', \'2024-12-13 16:32:42\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\AuthController.php(89): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
ERROR - 2024-12-13 16:32:48 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `us...', 0)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `us...')
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `us...')
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `us...', Array, false)
#4 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\ci\todo\app\Controllers\AuthController.php(89): CodeIgniter\BaseModel->save(Array)
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
#11 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#16 {main}
CRITICAL - 2024-12-13 16:32:48 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: register]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AuthController.php(89): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:32:48 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'sdasd\', \'vishwakarma888115@gmail.com\', \'$2y$10$lBgB3yz2MOW.bFHxVsp0g.OE6ZomEvfT38gMUQRfd6uGN7Rt1QvES\', \'1\', \'2024-12-13 16:32:48\', \'2024-12-13 16:32:48\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'sdasd\', \'vishwakarma888115@gmail.com\', \'$2y$10$lBgB3yz2MOW.bFHxVsp0g.OE6ZomEvfT38gMUQRfd6uGN7Rt1QvES\', \'1\', \'2024-12-13 16:32:48\', \'2024-12-13 16:32:48\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\AuthController.php(89): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:32:48 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'sdasd\', \'vishwakarma888115@gmail.com\', \'$2y$10$lBgB3yz2MOW.bFHxVsp0g.OE6ZomEvfT38gMUQRfd6uGN7Rt1QvES\', \'1\', \'2024-12-13 16:32:48\', \'2024-12-13 16:32:48\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'sdasd\', \'vishwakarma888115@gmail.com\', \'$2y$10$lBgB3yz2MOW.bFHxVsp0g.OE6ZomEvfT38gMUQRfd6uGN7Rt1QvES\', \'1\', \'2024-12-13 16:32:48\', \'2024-12-13 16:32:48\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (\'sdasd\', \'vishwakarma888115@gmail.com\', \'$2y$10$lBgB3yz2MOW.bFHxVsp0g.OE6ZomEvfT38gMUQRfd6uGN7Rt1QvES\', \'1\', \'2024-12-13 16:32:48\', \'2024-12-13 16:32:48\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `users` (`username`, `email`, `password`, `status`, `created_at`, `updated_at`) VALUES (:username:, :email:, :password:, :status:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\AuthController.php(89): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AuthController->registerUser()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AuthController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
ERROR - 2024-12-13 16:33:21 --> mysqli_sql_exception: Unknown column 'created_at' in 'field list' in D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php:312
Stack trace:
#0 D:\ci\todo\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `ad...', 0)
#1 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `ad...')
#2 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `ad...')
#3 D:\ci\todo\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `ad...', Array, false)
#4 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
#5 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(840): CodeIgniter\Model->doInsert(Array)
#6 D:\ci\todo\vendor\codeigniter4\framework\system\Model.php(802): CodeIgniter\BaseModel->insert(Array, false)
#7 D:\ci\todo\vendor\codeigniter4\framework\system\BaseModel.php(751): CodeIgniter\Model->insert(Array, false)
#8 D:\ci\todo\app\Controllers\AdminAuthController.php(87): CodeIgniter\BaseModel->save(Array)
#9 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(933): App\Controllers\AdminAuthController->registerAdmin()
#10 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminAuthController))
#11 D:\ci\todo\vendor\codeigniter4\framework\system\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(325): CodeIgniter\CodeIgniter->run()
#13 D:\ci\todo\vendor\codeigniter4\framework\system\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
#14 D:\ci\todo\public\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
#15 D:\ci\todo\vendor\codeigniter4\framework\system\rewrite.php(44): require_once('D:\\ci\\todo\\publ...')
#16 {main}
CRITICAL - 2024-12-13 16:33:21 --> CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
[Method: POST, Route: admin_register]
in SYSTEMPATH\Database\BaseConnection.php on line 688.
 1 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `admin` (`name`, `email`, `password_hash`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password_hash:, :created_at:, :updated_at:)', [...], false)
 2 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 3 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 4 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 5 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 6 APPPATH\Controllers\AdminAuthController.php(87): CodeIgniter\BaseModel->save([...])
 7 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdminAuthController->registerAdmin()
 8 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminAuthController))
 9 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
10 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
11 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
12 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
13 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:33:21 --> [Caused by] CodeIgniter\Database\Exceptions\DatabaseException: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 317.
 1 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `admin` (`name`, `email`, `password_hash`, `created_at`, `updated_at`) VALUES (\'Shubham Vishwakarma\', \'shiva83023@gmail.com\', \'$2y$10$.KKgi7xhTbjICk8GW1mGFOwXBquui4ezRMpDs5LkVGi3wmULVimdC\', \'2024-12-13 16:33:21\', \'2024-12-13 16:33:21\')')
 2 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `admin` (`name`, `email`, `password_hash`, `created_at`, `updated_at`) VALUES (\'Shubham Vishwakarma\', \'shiva83023@gmail.com\', \'$2y$10$.KKgi7xhTbjICk8GW1mGFOwXBquui4ezRMpDs5LkVGi3wmULVimdC\', \'2024-12-13 16:33:21\', \'2024-12-13 16:33:21\')')
 3 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `admin` (`name`, `email`, `password_hash`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password_hash:, :created_at:, :updated_at:)', [...], false)
 4 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 5 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 6 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 7 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 8 APPPATH\Controllers\AdminAuthController.php(87): CodeIgniter\BaseModel->save([...])
 9 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdminAuthController->registerAdmin()
10 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminAuthController))
11 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
12 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
13 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
14 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
15 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
CRITICAL - 2024-12-13 16:33:21 --> [Caused by] mysqli_sql_exception: Unknown column 'created_at' in 'field list'
in SYSTEMPATH\Database\MySQLi\Connection.php on line 312.
 1 SYSTEMPATH\Database\MySQLi\Connection.php(312): mysqli->query('INSERT INTO `admin` (`name`, `email`, `password_hash`, `created_at`, `updated_at`) VALUES (\'Shubham Vishwakarma\', \'shiva83023@gmail.com\', \'$2y$10$.KKgi7xhTbjICk8GW1mGFOwXBquui4ezRMpDs5LkVGi3wmULVimdC\', \'2024-12-13 16:33:21\', \'2024-12-13 16:33:21\')', 0)
 2 SYSTEMPATH\Database\BaseConnection.php(734): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `admin` (`name`, `email`, `password_hash`, `created_at`, `updated_at`) VALUES (\'Shubham Vishwakarma\', \'shiva83023@gmail.com\', \'$2y$10$.KKgi7xhTbjICk8GW1mGFOwXBquui4ezRMpDs5LkVGi3wmULVimdC\', \'2024-12-13 16:33:21\', \'2024-12-13 16:33:21\')')
 3 SYSTEMPATH\Database\BaseConnection.php(648): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `admin` (`name`, `email`, `password_hash`, `created_at`, `updated_at`) VALUES (\'Shubham Vishwakarma\', \'shiva83023@gmail.com\', \'$2y$10$.KKgi7xhTbjICk8GW1mGFOwXBquui4ezRMpDs5LkVGi3wmULVimdC\', \'2024-12-13 16:33:21\', \'2024-12-13 16:33:21\')')
 4 SYSTEMPATH\Database\BaseBuilder.php(2340): CodeIgniter\Database\BaseConnection->query('INSERT INTO `admin` (`name`, `email`, `password_hash`, `created_at`, `updated_at`) VALUES (:name:, :email:, :password_hash:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH\Model.php(394): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH\BaseModel.php(840): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH\Model.php(802): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH\BaseModel.php(751): CodeIgniter\Model->insert([...], false)
 9 APPPATH\Controllers\AdminAuthController.php(87): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH\CodeIgniter.php(933): App\Controllers\AdminAuthController->registerAdmin()
11 SYSTEMPATH\CodeIgniter.php(509): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\AdminAuthController))
12 SYSTEMPATH\CodeIgniter.php(355): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 SYSTEMPATH\Boot.php(325): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH\Boot.php(67): CodeIgniter\Boot::runCodeIgniter(Object(CodeIgniter\CodeIgniter))
15 FCPATH\index.php(56): CodeIgniter\Boot::bootWeb(Object(Config\Paths))
16 SYSTEMPATH\rewrite.php(44): require_once('D:\\ci\\todo\\public\\index.php')
